### ISSUE TITLE
Wiki Dedicated Server set up / unable to edit / rework into web page

### ISSUE THREAD

**Issue by Neoony** [EmpiresCommunity/website-hugo-deif#22]
Since its impossible to update https://wiki.empiresmod.com/Dedicated_Server_Setup

Idea is to rework it as a web page on empiresmod.com

Here it is with my edit included

[dedifull.txt](https://github.com/EmpiresCommunity/website-hugo-deif/files/7964755/dedifull.txt)

**Comment by smithy375** [comment]
- [ ] Migrate old page to a website article post. (Different formatting)
- [ ] Edit main page drop down link to point to the new article.
- [ ] Edit the old wiki page to instead act as a redirect.

**Comment by Neoony** [comment]
No longer needed as wiki should be fixed (still need to edit it though)
